################################################################################
# Module: Subnets
################################################################################
module "subnets" {
  for_each = { for map in local.subnets : map.subnet_name => map }
  source   = "github.com/oracle-quickstart/terraform-oci-networking//modules/subnet?ref=0.1.1"

  # Oracle Cloud Infrastructure Tenancy and Compartment OCID
  compartment_ocid = local.vcn_compartment_ocid
  vcn_id           = module.vcn.vcn_id

  # Deployment Tags + Freeform Tags + Defined Tags
  subnet_tags = local.oci_tag_values

  # Subnet arguments
  create_subnet              = local.create_subnets
  subnet_name                = each.value.subnet_name
  cidr_block                 = each.value.cidr_block
  display_name               = each.value.display_name # If null, is autogenerated
  dns_label                  = each.value.dns_label    # If null, is autogenerated
  prohibit_public_ip_on_vnic = each.value.prohibit_public_ip_on_vnic
  prohibit_internet_ingress  = each.value.prohibit_internet_ingress
  route_table_id             = each.value.route_table_id    # If null, the VCN's default route table is used
  dhcp_options_id            = each.value.dhcp_options_id   # If null, the VCN's default set of DHCP options is used
  security_list_ids          = each.value.security_list_ids # If null, the VCN's default security list is used
  ipv6cidr_block             = each.value.ipv6cidr_block    # If null, no IPv6 CIDR block is assigned
}

locals {
  subnets = [
    {
      subnet_name                = "5GC_OAM_subnet"
      cidr_block                 = lookup(local.network_cidrs, "SUBNET-5GC-OAM-CIDR")
      display_name               = "5GC OAM subnet (${local.deploy_id})"
      dns_label                  = "sn5gcoam${local.deploy_id}"
      prohibit_public_ip_on_vnic = true
      prohibit_internet_ingress  = true
      route_table_id             = module.route_tables["private"].route_table_id
      dhcp_options_id            = module.vcn.default_dhcp_options_id
      security_list_ids          = [module.security_lists["5gc_oam_security_list"].security_list_id]
      ipv6cidr_block             = null
    },
    {
      subnet_name                = "5GC_Signalling_subnet"
      cidr_block                 = lookup(local.network_cidrs, "SUBNET-5GC-SIGNALLING-CIDR")
      display_name               = "5GC Signalling (SBI) subnet (${local.deploy_id})"
      dns_label                  = "sn5gcsig${local.deploy_id}"
      prohibit_public_ip_on_vnic = true
      prohibit_internet_ingress  = true
      route_table_id             = module.route_tables["private"].route_table_id
      dhcp_options_id            = module.vcn.default_dhcp_options_id
      security_list_ids          = [module.security_lists["5gc_signalling_security_list"].security_list_id]
      ipv6cidr_block             = null
    },
    {
      subnet_name                = "5G_RAN_subnet"
      cidr_block                 = lookup(local.network_cidrs, "SUBNET-5G-RAN-CIDR")
      display_name               = "5G RAN subnet (${local.deploy_id})"
      dns_label                  = "sn5gran${local.deploy_id}"
      prohibit_public_ip_on_vnic = true
      prohibit_internet_ingress  = true
      route_table_id             = module.route_tables["private"].route_table_id
      dhcp_options_id            = module.vcn.default_dhcp_options_id
      security_list_ids          = [module.security_lists["5g_ran_security_list"].security_list_id]
      ipv6cidr_block             = null
    },
    {
      subnet_name                = "Legal_Intercept_subnet"
      cidr_block                 = lookup(local.network_cidrs, "SUBNET-LEGAL-INTERCEPT-CIDR")
      display_name               = "Legal Intercept subnet (${local.deploy_id})"
      dns_label                  = "snlegalin${local.deploy_id}"
      prohibit_public_ip_on_vnic = true
      prohibit_internet_ingress  = true
      route_table_id             = module.route_tables["private"].route_table_id
      dhcp_options_id            = module.vcn.default_dhcp_options_id
      security_list_ids          = [module.security_lists["legal_intercept_security_list"].security_list_id]
      ipv6cidr_block             = null
    },
    {
      subnet_name                = "5G_EPC_subnet"
      cidr_block                 = lookup(local.network_cidrs, "SUBNET-5G-EPC-CIDR")
      display_name               = "5G EPC subnet (${local.deploy_id})"
      dns_label                  = "sn5gcepc${local.deploy_id}"
      prohibit_public_ip_on_vnic = true
      prohibit_internet_ingress  = true
      route_table_id             = module.route_tables["private"].route_table_id
      dhcp_options_id            = module.vcn.default_dhcp_options_id
      security_list_ids          = [module.security_lists["5g_epc_security_list"].security_list_id]
      ipv6cidr_block             = null
    },
  ]
}
